'use strict';

var sugar = require('sugar');
var irc = require('irc');
var webSocket = require('ws');

var channel = '#atptest';
var webAddress = 'http://www.caseyliss.com/showbot';

var titles = [];
var connections = [];
var links = [];

function sendToAll(packet) {
    connections.forEach(function (connection) {
        connection.send(JSON.stringify(packet));
    });
}

function saveBackup() {
    // TODO: Figure out what to do here.
}

function handleNewSuggestion(from, message) {
    var titleValue;

    if (message.startsWith('!suggest')) {
        titleValue = message.substring(9);
    } else if (message.startsWith('!s')) {
        titleValue = message.substring(3);
    }

    if (titleValue.length > 75) {
        client.say(from, 'That title is too long; please try again.');
        titleValue = '';
    }
    if (titleValue.length > 0) {
        // Make sure this isn't a duplicate.
        if (titles.findAll({titleLower: titleValue.toLowerCase()}).length === 0) {
            var title = {
                id: titles.length,
                author: from,
                title: titleValue,
                titleLower: titleValue.toLowerCase(),
                votes: 0,
                votesBy: [],
                time: new Date()
            };
            titles.push(title);

            sendToAll({operation: 'NEW', title: title});
        } else {
            //client.say(channel, 'Sorry, ' + from + ', your title is a duplicate. Please try another!');
            client.say(from, 'Sorry, your title is a duplicate. Please try another!');
        }
    }
}

function handleSendVotes(from, message) {
    var titlesByVote = titles.sortBy(function (t) {
        return t.votes;
    }, true).to(3);

    client.say(from, 'Three most popular titles:');
    for (var i = 0; i < titlesByVote.length; ++i) {
        var votes = titlesByVote[i]['votes'];
        client.say(from, titlesByVote[i]['votes'] + ' vote' + (votes != 1 ? 's' : '') +  ': " ' + titlesByVote[i].title + '"');
    }
}

function handleNewLink(from, message) {
    if (message.startsWith('!link')) {
        message = message.substring(6);
    } else if (message.startsWith('!l')) {
        message = message.substring(3);
    }

    if (message.startsWith('http')) {
        var link = {
            id: links.length,
            author: from,
            link: message,
            time: new Date()
        };
        links.push(link);

        sendToAll({operation: 'NEWLINK', link: link});
    } else {
        client.say(from, "That doesn't look like a link to me.");
    }
}

function handleHelp(from) {
    client.say(from, 'Options:');
    client.say(from, '!s {title} - suggest a title.');
    client.say(from, '!votes - get the three most highly voted titles.');
    client.say(from, '!link {URL} - suggest a link.');
    client.say(from, '!help - see this message.');
    client.say(from, 'To see titles/links, go to: ' + webAddress);
}

var client = new irc.Client('irc.freenode.net', 'accidentalbot', {
    channels: [channel]
});

client.addListener('join', function (channel, nick, message) {
    console.log('Joined channel ' + channel);
    setInterval(saveBackup, 300000);
});

client.addListener('message', function (from, to, message) {
    var title = '';

    if (message.startsWith('!s')) {
        handleNewSuggestion(from, message);
    } else if (message.startsWith("!votes")) {
        handleSendVotes(from, message);
    } else if (message.startsWith('!l')) {
        handleNewLink(from, message);
    } else if (message.startsWith('!help')) {
        handleHelp(from);
    }
});

client.addListener('error', function (message) {
    console.log('error: ', message)
});

/***************************************************
 * WEB SOCKETS                                     *
 ***************************************************/

var port = Number(process.env.PORT || 5001);
var socketServer = new webSocket.Server({port: port});

function getRequestAddress(request) {
    // XXX: This assume that the X-Forwarded-For header is generated by a
    // XXX: trusted proxy. If not, a malicious user can take advantage of this
    // XXX: logic and use the header to spoof their IP, avoiding rate limiting.
    if ('x-forwarded-for' in request.headers) {
        var forwardedForAddresses = request.headers['x-forwarded-for'].split(',');
        if (forwardedForAddresses.length > 0) {
            return forwardedForAddresses[forwardedForAddresses.length - 1];
        }
    }

    return request.connection.remoteAddress;
}

socketServer.on('connection', function(socket) {
    connections.push(socket);

    var address = getRequestAddress(socket.upgradeReq);

    // Instead of sending all of the information about current titles to the
    // newly-connecting user, which would include the IP addresses of other
    // users, we just send down the information they need.
    var existingTitlesForUser = titles.map(function (title) {
        return {
            id: title.id,
            author: title.author,
            title: title.title,
            votes: title.votes,
            voted: title.votesBy.any(address),
            time: title.time
        };
    });
    console.log(JSON.stringify(existingTitlesForUser));
    socket.send(JSON.stringify({operation: 'REFRESH', titles: existingTitlesForUser, links: links}));

    socket.on('close', function () {
        connections.splice(connections.indexOf(socket), 1);
    });

    socket.on('message', function (data, flags) {
        var packet = JSON.parse(data);
        if (packet.operation === 'VOTE') {
            var matches = titles.findAll({id: packet['id']});

            if (matches.length > 0) {
                var upvoted = matches[0];
                if (upvoted['votesBy'].any(address) == false) {
                    upvoted['votes'] = Number(upvoted['votes']) + 1;
                    upvoted['votesBy'].push(address);
                    sendToAll({operation: 'VOTE', votes: upvoted['votes'], id: upvoted['id']});
                    console.log('+1 for ' + upvoted['title'] + ' by ' + address);
                } else {
                    console.log('ignoring duplicate vote by ' + address + ' for ' + upvoted['title']);
                }
            } else {
                console.log('no matches for id: ' + packet['id']);
            }
        } else if (packet.operation === 'PING') {
            socket.send(JSON.stringify({operation: 'PONG'}));
        } else {
            console.log("Don't know what to do with " + packet['operation']);
        }
    });
});
